blank_issues_enabled: false
contact_links:
  - name: Forum
    url: https://groups.google.com/g/tvb-users
    about: For questions about analysis and usage, and announcements of interest to the TVB community
